<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\address.png" />
    <None Remove="Images\cupons.png" />
    <None Remove="Images\exit.png" />
    <None Remove="Images\help.png" />
    <None Remove="Images\profile.png" />
    <None Remove="Images\settings.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\address.png" />
    <EmbeddedResource Include="Images\cupons.png" />
    <EmbeddedResource Include="Images\exit.png" />
    <EmbeddedResource Include="Images\help.png" />
    <EmbeddedResource Include="Images\profile.png" />
    <EmbeddedResource Include="Images\settings.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAuthentication.net" Version="3.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2196" />
    <PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Help.xaml.cs">
      <DependentUpon>Help.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\LoginScreen.xaml.cs">
      <DependentUpon>LoginScreen.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\News.xaml.cs">
      <DependentUpon>News.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\RegisterScreen.xaml.cs">
      <DependentUpon>RegisterScreen.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\AddAddressView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AddressListView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Categories.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ForgotPassword.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Home.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\News.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Profile.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\RegisterScreen.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\TabbedPage1.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>